version: 2.1

executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:bullseye

jobs:
  build-and-publish:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.6
      - run:
          name: Build image
          command: ./build
      - run:
          name: Publish images
          command: ./publish

workflows:
  version: 2
  build-master:
    jobs:
      - build-and-publish:
          filters:
            branches:
              only: master
